#!/bin/sh
set -aeu
find_earliest_date() {
    directory="${1}"
    {
        find \
            "${directory}" \
            -print0 \
        | xargs -0 \
            --no-run-if-empty \
            stat --print="%w	%x	%y	%z\n" \
        | awk -F'	' '{
            if($1 != "-") print $1;
            else if($3 != "-") print $3;
            else if($2 != "-") print $2;
            else if($4 != "-") print $4;
            else print "";
        }' \
        ;
        find \
            "${directory}" \
            -type f \
            -name '*.nfo' \
            -print0 \
        | xargs -0 \
            --no-run-if-empty \
            grep '<dateadded>.*</dateadded>' \
            --only-matching \
            --no-filename \
        | sed 's@\s*<[^>]*>@@g' \
        ;
    } \
    | grep -v '^\s*$' \
    | sed 's@\..*$@@' \
    | sort \
    | head -n1 \
    ;
}
NFO_BASE=tvshow.nfo
XSLT_BASE=tvshow.xslt
for video in "${@}"
do
    video="$(realpath --no-symlinks "${video}")"
    video_base="${video%.*}"
    video_dir="$(dirname "${video}")"
    nfo="${video_base}.nfo"
    now="$(date '+%Y-%m-%d %H:%M:%S')"
    nfo_pass1=/tmp/kodi.nfo
    nfo_pass2=/tmp/kodi2.nfo
    nfo_pass_break="${nfo_pass1}.bak"
    style="${XSLT_BASE}"
    if [ -e "${nfo}" ]
    then
        created="$(stat "${video}" | grep 'Modify:' | sed 's/Modify: //; s/\..*$//;')"
        echo "${nfo}: ${created}"
        saxonb -o "${nfo_pass1}" "${nfo}" "${style}" "current-datetime=${now}" "created-datetime=${created}"
        echo >>"${nfo_pass1}"
        # vimdiff "${nfo_pass1}" "${nfo}"
        filesize="$(cat "${nfo_pass1}" | wc -l)"
        if [ -e "${nfo_pass_break}" ] || [ "${filesize:-0}" -lt 3 ]
        then
            break
        fi
        if ! diff "${nfo_pass1}" "${nfo}" >/dev/null
        then
            saxonb -o "${nfo_pass2}" "${nfo_pass1}" "${style}" "current-datetime=${now}" "created-datetime=${created}" "update-datetime=1"
            echo >>"${nfo_pass2}"
            cp "${nfo_pass2}" "${nfo}"
        fi
    else
        echo "${video}"
        echo "${video_base}"
        echo "${video_dir}"
        echo "${nfo}"
        printf 'Unable to find nfo for %s: ' "${video}"
        find "${video_dir}" -mindepth 1 -maxdepth 1 -print0 \
        | sed --null-data 's@^.*\/@@' \
        | xargs -0 \
        ;
    fi
done
if [ -e /tmp/kodi.nfo.break ]
then
    rm /tmp/kodi.nfo.break
fi
